### ISSUE TITLE
Bug with prices

### ISSUE THREAD

**Issue by A11lyFi** [AydievMansur/price_parse_chrome#2]
Mate i just find out ur topic a few minutes ago at forum,download ur plugin and find a few bugs.
![image](https://user-images.githubusercontent.com/58190677/69576096-10ae3080-0fe5-11ea-9a82-4330ad540ada.png)
I think its because you are using parseFloat and then trying push it into parseInt.
Hopefully you fix it asap.
regards Ally.

**Comment by AydievMansur** [comment]
> Mate i just find out ur topic a few minutes ago at forum,download ur plugin and find a few bugs.
> ![image](https://user-images.githubusercontent.com/58190677/69576096-10ae3080-0fe5-11ea-9a82-4330ad540ada.png)
> I think its because you are using parseFloat and then trying push it into parseInt.
> Hopefully you fix it asap.
> regards Ally.

Thanks for take your time, i try to figure out what happen with calculation and shortly try to fix it, you can also create pull request.

**Comment by AydievMansur** [comment]
Fixed, also made auto parse & convert every 1 sec.
Full support tradeit.gg
